### ISSUE TITLE
kernel version limit -- eBPF

### ISSUE THREAD

**Issue by WhatDaniel** [eurecom-s3/x-ray-tls#1]
I tried this project, and it did catch the right keys. Very good!
Also i want to mention it would be better to declare that it need kernel version > 5.8, or it will fail to use ring_buffer.
And i found that it affected the normal termination of the "commands" process.
Maybe i misconfigured it, i will try it more.

**Comment by fl42** [comment]
Hello,

Thank you for the info. We will update the doc accordingly.
